# Generated by Django 6.0.3 on 2026-06-10 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_client_table_remove_order_table_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='status',
            field=models.CharField(choices=[('free', 'Libre'), ('occuped', 'Occupee')], default='free', max_length=20),
        ),
    ]
